### ISSUE TITLE
Wizard Contexts need to persist better

### ISSUE THREAD

**Issue by Olliebrown** [UWStout/eec-common#18]
**Current Behavior**
Presently, when a new session starts or re-starts then entire wizard interface refreshes, losing all history and sometimes even changing what tab you have selected.

**Expected Behavior**
When a session update is received, only new sessions that were previously not there should be added and others should not change, lose their data, or otherwise refresh.

The currently selected tab should not change unless the wizard clicks off of it.

Ended or expired sessions should persist so they can be reviewed or restored if the client re-connects.  Stale sessions should disable the send button with a note that says 'inactive' to indicate that you cannot send while it is offline.

### Tasks
- ~Store session history in 'session' storage so it persists when sessions update~
- [x] Quickly compute delta when a new session is announced
- [x] Only add new sessions and invalidate old ones, do not change ones that persist
- [x] Track status and keep expired sessions around but make them 'inactive' or 'invalid'
- [x] Allow sessions that restore to re-connect to a previous session for consistency (don't create a new tab, re-active an old one)
