### ISSUE TITLE
Using Real Data in Popup and Connect Panel

### ISSUE THREAD

**Issue by Olliebrown** [UWStout/eec-common#7]
We need to get the Karuna Connect Panel and popup to use real data from the database whenever possible.  This is often held up by the endpoints not existing or not being correct.

- [x] Build ajax request for affect history (~waiting on issue #2~)
- [x] Build ajax request for user status icons (~waiting on issue #8~)
- [x] Populate status icons from the ajax request (~waiting on issue #8~)
- [x] Build ajax requests for updating user status from connect panel (~waiting on issue #8~)
- [x] Connect status updates (mood/collab) to ajax request (~waiting on issue #8~)

I'm going to move the rest of these to a future issue.  They really aren't needed for the Alpha.
- Populate history menu from the ajax request (~waiting on issue #2~)
- Build ajax requests for updating popup teams
- Connect teams updates to ajax request
- Build ajax requests for Karuna Settings (timeout and non-project related messages)
- Connect Karuna Settings updates to ajax request
